### ISSUE TITLE
Peer dependencies in packages use a beta version of fetchye-core

### ISSUE THREAD

**Issue by smackfu** [americanexpress/fetchye#50]
# 🐞 Bug Report

## Describe the bug

The packages that depend on fetchye-core are using a beta version (`^1.0.0-beta.4`) in the peerDependency listing in their package.json files.  I doubt this is intentional... it looks like lerna just does not automatically update the version of peer dependencies to match the overall package version.
https://github.com/lerna/lerna/issues/1575  

Example:
https://github.com/americanexpress/fetchye/blob/f150f6deb90e0ecc11f269156220b66b8b40b789/packages/fetchye-immutable-cache/package.json#L51

## Expected behavior

Ideally, the version in the peerDeps would match the overall package version.  If that is not technically possible, it should be changed to a non-beta semver pattern like `^1.0.0`.

**Comment by JAdshead** [comment]
we could also set to `*` similar to fetchye
